sudo: false
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "5"
  - "6"
  - "7"
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn install-peers && yarn lint && yarn test
