sudo: false
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "5"
  - "6"
  - "7"
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before-script:
  - npm install-peers 
script:
  - yarn lint && yarn test
