sudo: false
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "5"
  - "6"
  - "7"
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - npm install -g $(npm --version)
  - npm run install-peers
script:
  - npm run lint && npm run test
